controller:
  ingressClassResource:
    default: true
  service:
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
      service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "ass-dt-we-008-vnet-01"